# Generated by Django 5.2.7 on 2025-11-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(max_length=50, unique=True, verbose_name='کد جایگاه')),
                ('position_group', models.CharField(max_length=100, verbose_name='گروه جایگاه')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان جایگاه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'جایگاه سازمانی',
                'verbose_name_plural': 'جایگاه\u200cهای سازمانی',
                'ordering': ['position_code'],
            },
        ),
    ]
