# Generated by Django 5.2.7 on 2025-11-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalposition',
            name='position_parent_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سرگروه جایگاه'),
        ),
        migrations.AlterField(
            model_name='organizationalposition',
            name='position_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='گروه جایگاه'),
        ),
    ]
