# Generated by Django 5.2.7 on 2025-11-09 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_position', '0002_organizationalposition_position_parent_group_and_more'),
        ('soldires_apps', '0027_soldier_position_soldier_position_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalposition',
            name='soldier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_solider', to='soldires_apps.soldier', verbose_name='سرباز دارنده جایگاه فعلی'),
        ),
    ]
