# Generated by Django 5.1.4 on 2025-04-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_leave_quota', models.PositiveIntegerField(default=0, verbose_name='سقف مرخصی استحقاقی')),
                ('incentive_leave_quota', models.PositiveIntegerField(default=0, verbose_name='سقف مرخصی تشویقی')),
                ('sick_leave_quota', models.PositiveIntegerField(default=0, verbose_name='سقف مرخصی استعلاجی')),
                ('annual_leave_used', models.PositiveIntegerField(default=0, verbose_name='تعداد مرخصی استحقاقی استفاده شده')),
                ('incentive_leave_used', models.PositiveIntegerField(default=0, verbose_name='تعداد مرخصی تشویقی استفاده شده')),
                ('sick_leave_used', models.PositiveIntegerField(default=0, verbose_name='تعداد مرخصی استعلاجی استفاده شده')),
                ('annual_leave_remaining', models.PositiveIntegerField(default=0, verbose_name='تعداد مرخصی استحقاقی مانده')),
                ('incentive_leave_remaining', models.PositiveIntegerField(default=0, verbose_name='تعداد مرخصی تشویقی مانده')),
                ('sick_leave_remaining', models.PositiveIntegerField(default=0, verbose_name='تعداد مرخصی استعلاجی مانده')),
                ('extra_sick_leave_quota', models.PositiveIntegerField(default=0, verbose_name='سقف مازاد استعلاجی')),
                ('extra_annual_leave_quota', models.PositiveIntegerField(default=0, verbose_name='سقف مازاد استحقاقی')),
            ],
        ),
    ]
