# Generated by Django 5.1.4 on 2025-04-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldier_vacation_apps', '0001_initial'),
        ('soldires_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='soldier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier'),
        ),
    ]
