# Generated by Django 5.1.4 on 2025-05-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_vacation_apps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='initial_annual_leave_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='سقف اولیه مرخصی استحقاقی کمکی'),
        ),
    ]
