# Generated by Django 5.1.4 on 2025-05-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_vacation_apps', '0003_leavebalance_initial_annual_leave_quota'),
        ('soldires_apps', '0022_soldier_eye_color_soldier_hair_color_soldier_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='soldier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier'),
        ),
    ]
