# Generated by Django 5.1.4 on 2024-12-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Parent Unit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Sub Unit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='units_apps.parentunit', verbose_name='Parent Unit')),
                ('sub_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sub_units', to='units_apps.subunit', verbose_name='Parent Sub Unit')),
            ],
        ),
    ]
