# Generated by Django 5.1.4 on 2025-04-27 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldires_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام واحد اصلی')),
            ],
            options={
                'verbose_name': 'واحد اصلی',
                'verbose_name_plural': 'واحدهای اصلی',
            },
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام زیرواحد')),
                ('parent_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='units_apps.parentunit', verbose_name='واحد اصلی')),
            ],
            options={
                'verbose_name': 'زیرواحد',
                'verbose_name_plural': 'زیرواحدها',
            },
        ),
        migrations.CreateModel(
            name='UnitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('skill_training_workshop', models.BooleanField(default=False, verbose_name='کارگاه مهات آموزی')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.parentunit', verbose_name='واحد اصلی')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_history', to='soldires_apps.soldier', verbose_name='سرباز')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.subunit', verbose_name='زیرواحد')),
            ],
            options={
                'verbose_name': 'تاریخچه بخش خدمت',
                'verbose_name_plural': 'تاریخچه بخش\u200cهای خدمت',
            },
        ),
    ]
