# Generated by Django 5.1.4 on 2024-12-23 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentunit',
            options={'verbose_name': 'واحد اصلی', 'verbose_name_plural': 'واحدهای اصلی'},
        ),
        migrations.AlterModelOptions(
            name='subunit',
            options={'verbose_name': 'زیرواحد', 'verbose_name_plural': 'زیرواحدها'},
        ),
        migrations.RemoveField(
            model_name='parentunit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='sub_parent',
        ),
        migrations.AlterField(
            model_name='parentunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام واحد اصلی'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام زیرواحد'),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='parent_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='units_apps.parentunit', verbose_name='واحد اصلی'),
        ),
    ]
