# Generated by Django 5.1.4 on 2025-04-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='work_type',
            field=models.CharField(blank=True, choices=[('اداری', 'اداری'), ('شیفتی', 'شیفتی'), ('پستی', 'پستی')], max_length=50, null=True, verbose_name='تردد'),
        ),
    ]
