# Generated by Django 5.1.4 on 2025-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units_apps', '0002_subunit_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='HealthIodine',
            field=models.BooleanField(default=False, verbose_name='دریافت تائیدیه سلامت'),
        ),
    ]
