# Generated by Django 5.1.4 on 2024-12-23 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0002_remove_soldier_subunit_name_remove_soldier_unit_name_and_more'),
        ('units_apps', '0002_alter_parentunit_options_alter_subunit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.parentunit', verbose_name='واحد اصلی')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_history', to='soldires_apps.soldier', verbose_name='سرباز')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.subunit', verbose_name='زیرواحد')),
            ],
            options={
                'verbose_name': 'تاریخچه بخش خدمت',
                'verbose_name_plural': 'تاریخچه بخش\u200cهای خدمت',
            },
        ),
    ]
