# Generated by Django 5.1.4 on 2025-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units_apps', '0003_unithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='unithistory',
            name='skill_training_workshop',
            field=models.BooleanField(default=False, verbose_name='کارگاه مهات آموزی'),
        ),
    ]
