# Generated by Django 5.2.6 on 2025-09-23 20:37

import analystics.models
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EshrafAnalyze",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("date", django_jalali.db.models.jDateField(verbose_name="تاریخ")),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("سه ماهه اول", "سه ماهه اول"),
                            ("سه ماهه دوم", "سه ماهه دوم"),
                            ("سه ماهه سوم", "سه ماهه سوم"),
                            ("سه ماهه چهارم", "سه ماهه چهارم"),
                        ],
                        max_length=20,
                        verbose_name="دوره",
                    ),
                ),
                (
                    "file_1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 1",
                    ),
                ),
                (
                    "file_2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 2",
                    ),
                ),
                (
                    "file_3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 3",
                    ),
                ),
                (
                    "file_4",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 4",
                    ),
                ),
                (
                    "file_5",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 5",
                    ),
                ),
                (
                    "file_6",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 6",
                    ),
                ),
                (
                    "file_7",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 7",
                    ),
                ),
                (
                    "file_8",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 8",
                    ),
                ),
                (
                    "file_9",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 9",
                    ),
                ),
                (
                    "file_10",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analystics.models.upload_to_analyze,
                        verbose_name="فایل 10",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل اشراف",
                "verbose_name_plural": "فایل\u200cهای اشراف",
            },
        ),
    ]
