# Generated by Django 5.2.6 on 2025-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analystics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eshrafanalyze",
            name="date",
            field=models.DateField(verbose_name="تاریخ"),
        ),
    ]
