# Generated by Django 5.1.4 on 2025-05-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع فرار')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بازگشت از فرار')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escapes', to='soldires_apps.soldier')),
            ],
            options={
                'verbose_name': 'سابقه فرار',
                'verbose_name_plural': 'سوابق فرار',
                'ordering': ['-start_date'],
            },
        ),
    ]
