# Generated by Django 5.1.4 on 2025-05-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('service_completed', 'پایان خدمت'), ('university_admission', 'قبولی در دانشگاه'), ('transfer', 'انتقال'), ('permanent_exemption', 'معافیت دائم')], max_length=30, verbose_name='علت تسویه حساب')),
                ('letter_number', models.CharField(max_length=50, verbose_name='شماره نامه')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور تسویه کل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier', verbose_name='سرباز')),
            ],
            options={
                'verbose_name': 'نامه تسویه\u200cحساب',
                'verbose_name_plural': 'نامه\u200cهای تسویه\u200cحساب',
            },
        ),
    ]
