# Generated by Django 5.1.4 on 2025-05-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceletter',
            name='status',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('in_process', 'چاپ ودرحال بررسی'), ('approved', 'تأیید نهایی')], default='created', max_length=100, verbose_name='وضعیت نامه'),
        ),
        migrations.AlterField(
            model_name='clearanceletter',
            name='issue_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ صدور تسویه کل'),
        ),
        migrations.AlterField(
            model_name='clearanceletter',
            name='letter_number',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='شماره نامه'),
        ),
    ]
