# Generated by Django 5.1.4 on 2025-05-14 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0002_clearanceletter_status_and_more'),
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceletter',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و درحال بررسی', 'چاپ و درحال بررسی'), ('تأیید نهایی', 'تأیید نهایی')], default='ایجاد شده', max_length=100, verbose_name='وضعیت نامه'),
        ),
        migrations.CreateModel(
            name='NormalLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='شماره نامه')),
                ('letter_type', models.CharField(choices=[('membership', 'گواهی عضویت'), ('service', 'گواهی اشتغال به خدمت'), ('request', 'نامه درخواست'), ('other', 'سایر')], max_length=20, verbose_name='نوع نامه')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ نامه')),
                ('destination', models.CharField(max_length=255, verbose_name='مقصد نامه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('reviewed', 'چاپ و بررسی شده'), ('approved', 'تایید شده')], default='created', max_length=10, verbose_name='وضعیت نامه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier', verbose_name='سرباز')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه\u200cها',
            },
        ),
    ]
