# Generated by Django 5.1.4 on 2025-05-14 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0003_alter_clearanceletter_status_normalletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalLetterMentalHealthAssessmentAndEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('entry_test', 'تست سلامت بدو ورود'), ('return_test', 'تست سلامت پس از بازگشت از فرار')], max_length=50, verbose_name='موضوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('normal_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
            ],
            options={
                'verbose_name': 'تست سلامت روان',
                'verbose_name_plural': 'تست\u200cهای سلامت روان',
            },
        ),
    ]
