# Generated by Django 5.1.4 on 2025-05-14 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0004_normallettermentalhealthassessmentandevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normallettermentalhealthassessmentandevaluation',
            name='normal_letter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی'),
        ),
        migrations.CreateModel(
            name='NormalLetterJudicialInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('پایان خدمت', 'پایان خدمت'), ('قبولی در دانشگاه', 'قبولی در دانشگاه'), ('ماه پایانی خدمت', 'ماه پایانی خدمت'), ('معافیت پزشکی', 'معافیت پزشکی'), ('انتقال', 'انتقال')], max_length=30, verbose_name='علت استعلام')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('normal_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
            ],
            options={
                'verbose_name': 'استعلام قضایی',
                'verbose_name_plural': 'استعلام\u200cهای قضایی',
            },
        ),
    ]
