# Generated by Django 5.1.4 on 2025-05-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0005_alter_normallettermentalhealthassessmentandevaluation_normal_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalLetterDomesticSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('پایان خدمت', 'پایان خدمت'), ('قبولی در  دانشگاه', 'قبولی در  دانشگاه'), ('جابجایی', 'جابجایی'), ('انتقال', 'انتقال'), ('معافیت کفالت', 'معافیت کفالت')], max_length=30, verbose_name='علت تسویه حساب')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('normal_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
            ],
            options={
                'verbose_name': 'تسویه حساب داخلی',
                'verbose_name_plural': 'تسویه حساب های داخلی',
            },
        ),
    ]
