# Generated by Django 5.1.4 on 2025-05-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0006_normalletterdomesticsettlement'),
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
        ('units_apps', '0002_subunit_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroductionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=50, unique=True, verbose_name='شماره نامه')),
                ('letter_date', models.DateField(auto_now_add=True, verbose_name='تاریخ نامه')),
                ('letter_type', models.CharField(choices=[('introduce', 'معرفی\u200cنامه'), ('four_page', 'چهاربرگ')], default='introduce', max_length=20, verbose_name='نوع نامه')),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('introduced', 'معرفی شده'), ('printed', 'چاپ شده'), ('reviewed', 'بررسی شده'), ('approved', 'تایید مسئول')], default='created', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.parentunit', verbose_name='قسمت معرفی\u200cشده')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier', verbose_name='سرباز')),
                ('sub_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.subunit', verbose_name='زیرقسمت')),
            ],
            options={
                'verbose_name': 'نامه',
                'verbose_name_plural': 'نامه\u200cها',
            },
        ),
    ]
