# Generated by Django 5.1.4 on 2025-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0007_introductionletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalletter',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و بررسی شده', 'چاپ و بررسی شده'), ('تایید شده', 'تایید شده')], default='ایجاد شده', max_length=100, verbose_name='وضعیت نامه'),
        ),
    ]
