# Generated by Django 5.1.4 on 2025-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0008_alter_normalletter_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introductionletter',
            options={'verbose_name': 'معرفی نامه', 'verbose_name_plural': 'معرفی نامه ها'},
        ),
        migrations.AlterField(
            model_name='introductionletter',
            name='letter_type',
            field=models.CharField(choices=[('معرفی\u200cنامه', 'معرفی\u200cنامه'), ('چهاربرگ', 'چهاربرگ')], default='introduce', max_length=20, verbose_name='نوع نامه'),
        ),
        migrations.AlterField(
            model_name='introductionletter',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و درحال بررسی', 'چاپ و درحال بررسی'), ('تأیید نهایی', 'تأیید نهایی')], default='created', max_length=20, verbose_name='وضعیت'),
        ),
    ]
