# Generated by Django 5.1.4 on 2025-05-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0009_alter_introductionletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalletter',
            name='date',
            field=models.DateField(verbose_name='تاریخ نامه'),
        ),
    ]
