# Generated by Django 5.1.4 on 2025-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0010_alter_normalletter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalletter',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
