# Generated by Django 5.1.4 on 2025-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0011_alter_normalletter_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='normalletter',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ نامه'),
        ),
    ]
