# Generated by Django 5.1.4 on 2025-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0012_alter_normalletter_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normallettermentalhealthassessmentandevaluation',
            name='created_at',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
    ]
