# Generated by Django 5.1.4 on 2025-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0013_alter_normallettermentalhealthassessmentandevaluation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normallettermentalhealthassessmentandevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
