# Generated by Django 5.1.4 on 2025-05-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0014_alter_normallettermentalhealthassessmentandevaluation_created_at'),
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('گواهی عضویت', 'گواهی عضویت'), ('گواهی پایان خدمت', 'گواهی پایان خدمت'), ('گواهی پایان دوره آموزش', 'گواهی پایان دوره آموزش'), ('تسویه حساب', 'تسویه حساب')], max_length=250, verbose_name='موضوع')),
                ('description_in', models.TextField(blank=True, null=True, verbose_name='توضیحات داخل نامه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('normal_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier', verbose_name='سرباز')),
            ],
            options={
                'verbose_name': 'نامه گواهی',
                'verbose_name_plural': 'نامه\u200cهای گواهی',
                'ordering': ['-id'],
            },
        ),
    ]
