# Generated by Django 5.1.4 on 2025-05-18 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0015_membershipcertificate'),
        ('units_apps', '0002_subunit_work_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalLetterHealthIodine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.parentunit', verbose_name='قسمت معرفی\u200cشده')),
                ('sub_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.subunit', verbose_name='زیرقسمت')),
            ],
            options={
                'verbose_name': 'نامه  تائیدیه سلامت',
                'verbose_name_plural': 'نامه\u200cهای  تائیدیه سلامت',
            },
        ),
    ]
