# Generated by Django 5.1.4 on 2025-05-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0016_normalletterhealthiodine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introductionletter',
            name='letter_type',
            field=models.CharField(choices=[('معرفی\u200cنامه', 'معرفی\u200cنامه'), ('چهاربرگ', 'چهاربرگ')], default='معرفی\u200cنامه', max_length=20, verbose_name='نوع نامه'),
        ),
        migrations.AlterField(
            model_name='introductionletter',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و درحال بررسی', 'چاپ و درحال بررسی'), ('تأیید نهایی', 'تأیید نهایی')], default='ایجاد شده', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='NormalLetterCommitmentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_card_chip', models.CharField(blank=True, choices=[('کارت', 'کارت'), ('تراشه', 'تراشه')], max_length=100, null=True, verbose_name='تراشه/کارت')),
                ('normal_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
            ],
            options={
                'verbose_name': 'تعهد نامه',
                'verbose_name_plural': 'تعهد نامه',
            },
        ),
    ]
