# Generated by Django 5.1.4 on 2025-05-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0017_alter_introductionletter_letter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceletter',
            name='reason',
            field=models.CharField(choices=[('پایان خدمت', 'پایان خدمت'), ('قبولی در دانشگاه', 'قبولی در دانشگاه'), ('انتقال', 'انتقال'), ('معافیت دائم', 'معافیت دائم')], max_length=30, verbose_name='علت تسویه حساب'),
        ),
        migrations.AlterField(
            model_name='introductionletter',
            name='letter_type',
            field=models.CharField(choices=[('معرفی\u200cنامه', 'معرفی\u200cنامه'), ('چهاربرگ+معرفی نامه', 'چهاربرگ+معرفی نامه')], default='معرفی\u200cنامه', max_length=20, verbose_name='نوع نامه'),
        ),
        migrations.AlterField(
            model_name='normalletter',
            name='letter_type',
            field=models.CharField(choices=[('membership', 'گواهی عضویت'), ('service', 'گواهی اشتغال به خدمت'), ('request', 'نامه درخواست'), ('other', 'سایر'), ('سنجش و ارزیابی سلامت روان', 'سنجش و ارزیابی سلامت روان')], max_length=250, verbose_name='نوع نامه'),
        ),
    ]
