# Generated by Django 5.2.6 on 2025-10-01 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soldire_letter_apps", "0018_alter_clearanceletter_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssentialFormCardLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "letter_type",
                    models.CharField(
                        choices=[
                            ("clearance_letter", "فرم شماره 3"),
                            ("officer_card", "صدور کارت پایور"),
                            ("soldier_card", "صدور کارت سرباز"),
                            ("checkout_3plus", "فرم تسویه حساب 3 فرزندی و بالاتر"),
                            ("activate_old_staff", "فعال سازی اعزام کارکنان قدیمی"),
                            ("certificate_two_guard", "گواهی دو پاسدار"),
                            ("permanent_exemption", "معافیت دائم کارکنان وظیفه"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_data",
                    models.JSONField(
                        blank=True,
                        help_text="ذخیره داده\u200cهای فرم به صورت JSON",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "فرم ضروری صدور کارت",
                "verbose_name_plural": "فرم\u200cهای ضروری صدور کارت",
                "ordering": ["-created_at"],
            },
        ),
    ]
