# Generated by Django 5.2.6 on 2025-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soldire_letter_apps", "0019_essential_forms_card_nezsa"),
    ]

    operations = [
        migrations.AddField(
            model_name="essentialformcardletter",
            name="number",
            field=models.CharField(
                blank=True, help_text="شماره نامه", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="essentialformcardletter",
            name="receiver",
            field=models.CharField(
                blank=True, help_text="به", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="essentialformcardletter",
            name="return_number",
            field=models.CharField(
                blank=True, help_text="شماره ارجاع/بازگشت", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="essentialformcardletter",
            name="sender",
            field=models.CharField(
                blank=True, help_text="از", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="essentialformcardletter",
            name="description",
            field=models.TextField(
                blank=True, help_text="توضیحات اضافی نامه", null=True
            ),
        ),
        migrations.AlterField(
            model_name="essentialformcardletter",
            name="letter_type",
            field=models.CharField(
                choices=[
                    ("clearance_letter", "فرم شماره 3"),
                    ("officer_card", "صدور کارت پایور"),
                    ("soldier_card", "صدور کارت سرباز"),
                    ("checkout_3plus", "فرم تسویه حساب 3 فرزندی و بالاتر"),
                    ("activate_old_staff", "فعال سازی اعزام کارکنان قدیمی"),
                    ("certificate_two_guard", "گواهی دو پاسدار"),
                    ("permanent_exemption", "معافیت دائم کارکنان وظیفه"),
                ],
                help_text="نوع فرم/نامه",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="essentialformcardletter",
            name="title",
            field=models.CharField(blank=True, help_text="عنوان نامه", max_length=200),
        ),
    ]
