# Generated by Django 5.2.7 on 2025-11-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0020_form_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearanceletter',
            name='expired_file_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پرونده منقضی'),
        ),
    ]
