# Generated by Django 5.2.7 on 2025-11-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0021_clearanceletter_expired_file_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='عنوان فرم')),
                ('file', models.FileField(upload_to='ready_forms/files/', verbose_name='فایل فرم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ready_forms/images/', verbose_name='تصویر فرم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('helper_text', models.TextField(blank=True, null=True, verbose_name='متن راهنما')),
                ('file_type', models.CharField(choices=[('pdf', 'پی دی اف'), ('docx', 'ورد'), ('xlsx', 'اکسل'), ('txt', 'متنی'), ('image', 'تصویر')], default='pdf', max_length=10, verbose_name='نوع فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرم آماده',
                'verbose_name_plural': 'فرم\u200cهای آماده',
            },
        ),
    ]
