# Generated by Django 5.2.7 on 2025-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0022_readyforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyforms',
            name='page_size',
            field=models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal'), ('A3', 'A3'), ('A5', 'A5')], default='A4', max_length=10, verbose_name='نوع صفحه'),
        ),
    ]
