# Generated by Django 5.2.7 on 2025-11-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0023_readyforms_page_size'),
        ('soldires_apps', '0027_soldier_position_soldier_position_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunawayLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و درحال بررسی', 'چاپ و درحال بررسی'), ('تأیید نهایی', 'تأیید نهایی')], default='ایجاد شده', max_length=50, verbose_name='وضعیت نامه')),
                ('letter_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت فرار')),
                ('absence_start_date', models.DateField(verbose_name='تاریخ شروع غیبت')),
                ('absence_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان غیبت')),
                ('letter_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='شماره نامه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('normal_letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier', verbose_name='سرباز')),
            ],
            options={
                'verbose_name': 'نامه فرار',
                'verbose_name_plural': 'نامه\u200cهای فرار',
                'ordering': ['-created_at'],
            },
        ),
    ]
