# Generated by Django 5.2.7 on 2025-11-24 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0024_runawayletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceletter',
            name='reason',
            field=models.CharField(choices=[('پایان خدمت', 'پایان خدمت'), ('قبولی در دانشگاه', 'قبولی در دانشگاه'), ('انتقال', 'انتقال'), ('معافیت دائم', 'معافیت دائم'), ('معافیت کفالت', 'معافیت کفالت')], max_length=30, verbose_name='علت تسویه حساب'),
        ),
        migrations.AlterField(
            model_name='clearanceletter',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و درحال بررسی', 'چاپ و درحال بررسی'), ('تأیید شده', 'تأیید شده'), ('تأیید نهایی', 'تأیید نهایی')], default='ایجاد شده', max_length=100, verbose_name='وضعیت نامه'),
        ),
        migrations.AlterField(
            model_name='introductionletter',
            name='letter_type',
            field=models.CharField(choices=[('معرفی\u200cنامه', 'معرفی\u200cنامه'), ('پنج\u200cبرگ', 'پنج برگ'), ('پنج\u200cبرگ+معرفی\u200cنامه', 'پنج برگ + معرفی نامه')], default='معرفی\u200cنامه', max_length=20, verbose_name='نوع نامه'),
        ),
        migrations.AlterField(
            model_name='normalletter',
            name='letter_type',
            field=models.CharField(choices=[('membership', 'گواهی عضویت'), ('service', 'گواهی اشتغال به خدمت'), ('request', 'نامه درخواست'), ('سنجش و ارزیابی سلامت روان', 'سنجش و ارزیابی سلامت روان'), ('other', 'سایر')], max_length=250, verbose_name='نوع نامه'),
        ),
        migrations.AlterField(
            model_name='runawayletter',
            name='normal_letter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soldire_letter_apps.normalletter', verbose_name='نامه عادی'),
        ),
    ]
