# Generated by Django 5.1.1 on 2025-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_letter_apps', '0025_alter_clearanceletter_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearanceletter',
            name='status',
            field=models.CharField(choices=[('ایجاد شده', 'ایجاد شده'), ('چاپ و درحال بررسی', 'چاپ و درحال بررسی'), ('تأیید شده', 'تأیید شده'), ('تأییدنهایی', 'تأیید نهایی')], default='ایجاد شده', max_length=100, verbose_name='وضعیت نامه'),
        ),
    ]
