# Generated by Django 5.1.4 on 2025-05-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_naserin_apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='naseringroup',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='naseringroup',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_nasserin', to=settings.AUTH_USER_MODEL, verbose_name='مدیر گروه'),
        ),
        migrations.AlterField(
            model_name='naseringroup',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام گروه'),
        ),
    ]
