# Generated by Django 5.2.7 on 2025-11-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredSoldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_file_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرونده منقضی')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=15, unique=True, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام پدر')),
                ('start_service_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع خدمت سربازی')),
                ('end_service_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان خدمت سربازی')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تسویه خدمت سربازی')),
                ('settlement_reason', models.CharField(blank=True, choices=[('END_OF_SERVICE', 'پایان خدمت'), ('TRANSFER', 'انتقال'), ('UNIVERSITY', 'قبولی در دانشگاه'), ('DEATH', 'فوتی'), ('OTHER', 'سایر')], max_length=50, null=True, verbose_name='دلیل تسویه')),
            ],
            options={
                'verbose_name': 'سرباز منقضی خدمت',
                'verbose_name_plural': 'سربازان منقضی خدمت',
                'ordering': ['-settlement_date'],
            },
        ),
    ]
