# Generated by Django 5.2.7 on 2025-11-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expired_soldiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiredsoldier',
            options={'ordering': ['-expired_file_number'], 'verbose_name': 'سرباز منقضی خدمت', 'verbose_name_plural': 'سربازان منقضی خدمت'},
        ),
        migrations.RemoveField(
            model_name='expiredsoldier',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='expiredsoldier',
            name='settlement_date',
        ),
        migrations.RemoveField(
            model_name='expiredsoldier',
            name='settlement_reason',
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='birth_certificate_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='expired_file',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پرونده'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='expired_reason',
            field=models.CharField(blank=True, choices=[('END_OF_SERVICE', 'پایان خدمت'), ('TRANSFER', 'انتقال'), ('UNIVERSITY', 'قبولی در دانشگاه'), ('DEATH', 'فوتی'), ('OTHER', 'سایر')], default='', max_length=50, null=True, verbose_name='دلیل منقضی شدن'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='organization_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='کد سربازی'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='review_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='بررسی وضعیت'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='expiredsoldier',
            name='expired_file_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره پرونده منقضی'),
        ),
        migrations.AlterField(
            model_name='expiredsoldier',
            name='father_name',
            field=models.CharField(default='', max_length=50, verbose_name='نام پدر'),
        ),
    ]
