# Generated by Django 5.2.7 on 2025-11-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expired_soldiers', '0002_alter_expiredsoldier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredsoldier',
            name='settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تسویه سرباز'),
        ),
    ]
