# Generated by Django 5.2.7 on 2025-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expired_soldiers', '0003_expiredsoldier_settlement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredsoldier',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='expiredsoldier',
            name='runaway_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ فرار از سربازی'),
        ),
        migrations.AlterField(
            model_name='expiredsoldier',
            name='expired_reason',
            field=models.CharField(blank=True, choices=[('END_OF_SERVICE', 'پایان خدمت'), ('ESCAPE', 'فرار'), ('STUDY', 'ادامه تحصیل'), ('DEATH', 'فوت'), ('TRANSFER_DUTY', 'انتقال.پایان ماموریت'), ('TRANSFER', 'انتقال'), ('DUTY', 'ماموریت'), ('EXPIRED', 'منقضی از خدمت')], default='', max_length=50, null=True, verbose_name='دلیل منقضی شدن'),
        ),
        migrations.AlterField(
            model_name='expiredsoldier',
            name='national_code',
            field=models.CharField(blank='true', default='', max_length=15, null=True, verbose_name='کد ملی'),
        ),
    ]
