# Generated by Django 5.1.4 on 2024-12-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام مرکز آموزشی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
            ],
        ),
    ]
