# Generated by Django 5.1.4 on 2025-04-27 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_apps', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('units_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='units',
            field=models.ManyToManyField(blank=True, to='units_apps.parentunit', verbose_name='واحد'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuser',
            name='features',
            field=models.ManyToManyField(blank=True, to='accounts_apps.feature'),
        ),
        migrations.AddField(
            model_name='managerpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerpermission',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_apps.permission'),
        ),
        migrations.AddField(
            model_name='accesshistory',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_apps.permission'),
        ),
    ]
