# Generated by Django 5.1.4 on 2025-01-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0001_initial'),
        ('units_apps', '0003_unithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Employment_status',
            field=models.CharField(blank=True, choices=[('سرباز', 'سرباز'), ('پاسدار', 'پاسدار'), ('کارمند', 'کارمند')], max_length=150, null=True, verbose_name='وضعیت شاغل'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='id_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کدپاسداری'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='units_apps.parentunit', verbose_name='واحد'),
        ),
    ]
