# Generated by Django 5.1.4 on 2025-04-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0002_initial'),
        ('units_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='units',
        ),
        migrations.AddField(
            model_name='myuser',
            name='parent_units',
            field=models.ManyToManyField(blank=True, to='units_apps.parentunit', verbose_name='واحدهای اصلی قابل مشاهده'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='features',
            field=models.ManyToManyField(blank=True, to='accounts_apps.feature', verbose_name='امکانات قابل دسترسی'),
        ),
    ]
