# Generated by Django 5.1.4 on 2025-04-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0003_remove_myuser_units_myuser_parent_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='parent_units',
            new_name='units',
        ),
    ]
