# Generated by Django 5.1.4 on 2025-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_apps', '0004_rename_parent_units_myuser_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
