# Generated by Django 5.1.4 on 2024-12-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldires_apps', '0002_remove_soldier_subunit_name_remove_soldier_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info_form', models.BooleanField(default=False, verbose_name='فرم اطلاعات فردی')),
                ('training_skills_form', models.BooleanField(default=False, verbose_name='فرم مهارت\u200cآموزی')),
                ('mental_health_form_training', models.BooleanField(default=False, verbose_name='برگه سلامت روان آموزشی')),
                ('introduction_letter', models.BooleanField(default=False, verbose_name='معرفی نامه (پاراف شده)')),
                ('green_dispatch_paper', models.BooleanField(default=False, verbose_name='برگه سبز اعزام')),
                ('training_center_referral_paper', models.BooleanField(default=False, verbose_name='برگه مراجعه به مرکز آموزش')),
                ('ideological_report_card', models.BooleanField(default=False, verbose_name='کارنامه عقیدتی')),
                ('sater_paper', models.BooleanField(default=False, verbose_name='برگه ساتر')),
                ('vaccination_paper', models.BooleanField(default=False, verbose_name='برگه واکسیناسیون')),
                ('green_training_paper', models.BooleanField(default=False, verbose_name='برگه سبز آموزشی')),
                ('educational_report_card', models.BooleanField(default=False, verbose_name='کارنامه آموزشی')),
                ('photo', models.BooleanField(default=False, verbose_name='عکس')),
                ('unit_mental_health_form', models.BooleanField(default=False, verbose_name='برگه سلامت روان یگان')),
                ('five_skills_certificate', models.BooleanField(default=False, verbose_name='گواهینامه ۵ گانه')),
                ('rank_certificate', models.BooleanField(default=False, verbose_name='حکم درجه')),
                ('chip_delivery_form', models.BooleanField(default=False, verbose_name='برگه تحویل تراشه')),
                ('national_card_copy', models.BooleanField(default=False, verbose_name='کپی کارت ملی')),
                ('id_card_copy', models.BooleanField(default=False, verbose_name='کپی شناسنامه')),
                ('spouse_national_card_copy', models.BooleanField(default=False, verbose_name='کپی کارت ملی همسر')),
                ('spouse_id_card_copy', models.BooleanField(default=False, verbose_name='کپی شناسنامه همسر')),
                ('marriage_certificate_copy', models.BooleanField(default=False, verbose_name='کپی ۴ صفحه اول سند ازدواج')),
                ('children_id_card_copy', models.BooleanField(default=False, verbose_name='کپی شناسنامه فرزندان')),
                ('blood_card_or_license', models.BooleanField(default=False, verbose_name='کارت خون یا گواهینامه')),
                ('protection_sheet', models.BooleanField(default=False, verbose_name='چهاربرگ (ته برگ حفاظت)')),
                ('supervision_sheet', models.BooleanField(default=False, verbose_name='چهاربرگ (ته برگ نظارت)')),
                ('ideological_sheet', models.BooleanField(default=False, verbose_name='چهاربرگ (ته برگ عقیدتی)')),
                ('judicial_sheet', models.BooleanField(default=False, verbose_name='چهاربرگ (ته برگ قضایی)')),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier', verbose_name='سرباز')),
            ],
        ),
    ]
