# Generated by Django 5.1.4 on 2025-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_documents_apps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldierdocuments',
            name='hokme_karo_gozini',
            field=models.BooleanField(default=False, verbose_name='حکم کارگزینی'),
        ),
    ]
