# Generated by Django 5.1.4 on 2025-05-13 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام سری کارت')),
                ('send_date', models.DateField(verbose_name='تاریخ ارسال سری')),
                ('status', models.CharField(choices=[('preparing', 'در حال آماده\u200cسازی'), ('sent', 'ارسال شده'), ('checking', 'در حال بررسی'), ('completed', 'تکمیل شده')], default='preparing', max_length=20, verbose_name='وضعیت سری')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شد؟')),
                ('is_issued', models.BooleanField(default=False, verbose_name='کارت صادر شده؟')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('note', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sends', to='soldires_apps.soldier')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sends', to='soldire_end_card.cardseries')),
            ],
        ),
    ]
