# Generated by Django 5.1.4 on 2025-04-28 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_iran_manager_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoare_sall', models.CharField(blank=True, max_length=250, null=True, verbose_name='شعار سال')),
                ('ostan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_iran_manager_apps.province', verbose_name='استان')),
            ],
        ),
    ]
