# Generated by Django 5.1.4 on 2025-05-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appssettings',
            name='essential_service_duration',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='مدت خدمت ضرورت'),
        ),
    ]
