# Generated by Django 5.1.4 on 2025-05-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0002_appssettings_essential_service_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appssettings',
            name='annual_leave_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='سقف مرخصی استحقاقی'),
        ),
        migrations.AddField(
            model_name='appssettings',
            name='incentive_leave_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='سقف مرخصی تشویقی'),
        ),
        migrations.AddField(
            model_name='appssettings',
            name='sick_leave_quota',
            field=models.PositiveIntegerField(default=0, verbose_name='سقف مرخصی استعلاجی'),
        ),
    ]
