# Generated by Django 5.1.4 on 2025-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0003_appssettings_annual_leave_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appssettings',
            name='Length_of_service_in_the_unit',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='مدت خدمت در یگان'),
        ),
    ]
