IMPORT_GROUP_SAMPLE_OBJ = [
    {
        "expired_file": "*",
        "expired_file_number": "۷۲۷۰",
        "national_code": "2150604736",
        "birth_certificate_number": "2150604736",
        "first_name": "سجاد",
        "last_name": "سیفی لر",
        "father_name": "ایمان",
        "organization_code": "100",
        "start_service_date": "1403/11/01",
        "end_service_date": "1405/01/01",
        "settlement_date": "1405/01/16",
        "expired_reason": "پایان خدمت",
        "review_status": "بررسی شد",
        "status": "فعال",
        "description": "---"
    },
    {
        "expired_file": "*",
        "expired_file_number": "۷۲۷۱",
        "national_code": "2150604737",
        "birth_certificate_number": "2150604737",
        "first_name": "رضا",
        "last_name": "محمدی",
        "father_name": "علی",
        "organization_code": "101",
        "start_service_date": "1403/12/01",
        "end_service_date": "1405/02/01",
        "settlement_date": "1405/02/15",
        "expired_reason": "فرار",
        "review_status": "در حال بررسی",
        "status": "غیرفعال",
        "description": "---"
    },
    {
        "expired_file": "*",
        "expired_file_number": "۷۲۷۲",
        "national_code": "2150604738",
        "birth_certificate_number": "2150604738",
        "first_name": "مریم",
        "last_name": "حسینی",
        "father_name": "احمد",
        "organization_code": "102",
        "start_service_date": "1403/10/15",
        "end_service_date": "1405/01/15",
        "settlement_date": "1405/01/30",
        "expired_reason": "ادامه تحصیل",
        "review_status": "بررسی شد",
        "status": "فعال",
        "description": "---"
    },
    {
        "expired_file": "*",
        "expired_file_number": "۷۲۷۳",
        "national_code": "2150604739",
        "birth_certificate_number": "2150604739",
        "first_name": "امیر",
        "last_name": "کریمی",
        "father_name": "حسین",
        "organization_code": "103",
        "start_service_date": "1403/09/20",
        "end_service_date": "1405/01/10",
        "settlement_date": "1405/01/25",
        "expired_reason": "انتقال",
        "review_status": "بررسی شد",
        "status": "فعال",
        "description": "---"
    },
    {
        "expired_file": "*",
        "expired_file_number": "۷۲۷۴",
        "national_code": "2150604740",
        "birth_certificate_number": "2150604740",
        "first_name": "لیلا",
        "last_name": "علیزاده",
        "father_name": "حسن",
        "organization_code": "104",
        "start_service_date": "1403/08/01",
        "end_service_date": "1405/01/05",
        "settlement_date": "1405/01/20",
        "expired_reason": "سایر",
        "review_status": "در حال بررسی",
        "status": "غیرفعال",
        "description": "---"
    },
]
