# Generated by Django 5.1.4 on 2024-12-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldires_apps', '0002_remove_soldier_subunit_name_remove_soldier_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksr_razmangan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ksr_janbazi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ksr_basij', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ksr_project', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ksr_farzand', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ksr_hamsar', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ksr_mantaqe_amaliati', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('khod_dore_senavati', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('khod_enzebati', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('khod_khalla', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('khod_samane', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('khod_ghayre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_ksr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_khod', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier')),
            ],
        ),
    ]
