# Generated by Django 5.1.4 on 2025-04-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduction_veterans', models.PositiveIntegerField(default=0, verbose_name='کسری رزمندگان')),
                ('reduction_disability', models.PositiveIntegerField(default=0, verbose_name='کسری جانبازی')),
                ('reduction_bsj', models.PositiveIntegerField(default=0, verbose_name='کسری بسیج')),
                ('reduction_project', models.PositiveIntegerField(default=0, verbose_name='کسری پروژه')),
                ('reduction_children', models.PositiveIntegerField(default=0, verbose_name='کسری فرزند')),
                ('reduction_spouse', models.PositiveIntegerField(default=0, verbose_name='کسری همسر')),
                ('reduction_operational_areas', models.PositiveIntegerField(default=0, verbose_name='کسری مناطق عملیاتی')),
                ('reduction_seniority', models.PositiveIntegerField(default=0, verbose_name='بخشش سنواتی')),
                ('reduction_non_local', models.PositiveIntegerField(default=0, verbose_name='کسر غیربومی')),
                ('reduction_system_adjustment', models.PositiveIntegerField(default=0, verbose_name='تطبیق با سامانه')),
                ('reduction_other', models.PositiveIntegerField(default=0, verbose_name='غیره')),
                ('reduction_total', models.PositiveIntegerField(default=0, verbose_name='مجموع کسری خدمت')),
                ('addition_seniority', models.PositiveIntegerField(default=0, verbose_name='سنواتی')),
                ('addition_discipline', models.PositiveIntegerField(default=0, verbose_name='انضباطی')),
                ('addition_gap', models.PositiveIntegerField(default=0, verbose_name='خلاء')),
                ('addition_system', models.PositiveIntegerField(default=0, verbose_name='سامانه')),
                ('addition_other', models.PositiveIntegerField(default=0, verbose_name='غیره')),
                ('addition_total', models.PositiveIntegerField(default=0, verbose_name='مجموع اضافه خدمت')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعزام')),
                ('service_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان خدمت اصلی')),
                ('actual_service_end_date', models.DateField(blank=True, null=True, verbose_name='پایان خدمت اصلی')),
                ('calculate_until_date', models.DateField(blank=True, null=True, verbose_name='محاسبه تا تاریخ')),
                ('main_service_days', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='خدمت اصلی به روز')),
                ('secondary_service_days', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='کمکی (خدمت اصلی)')),
                ('mandatory_service_months', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='خدمت دوره ضرورت (به ماه)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
