# Generated by Django 5.1.4 on 2025-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_service_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldierservice',
            name='khod_dore_senavati',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='khod_enzebati',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='khod_ghayre',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='khod_khalla',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='khod_samane',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_basij',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_farzand',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_hamsar',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_janbazi',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_mantaqe_amaliati',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_project',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='ksr_razmangan',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='total_khod',
        ),
        migrations.RemoveField(
            model_name='soldierservice',
            name='total_ksr',
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='actual_service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='پایان خدمت اصلی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='addition_discipline',
            field=models.PositiveIntegerField(default=0, verbose_name='انضباطی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='addition_gap',
            field=models.PositiveIntegerField(default=0, verbose_name='خلاء'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='addition_other',
            field=models.PositiveIntegerField(default=0, verbose_name='غیره'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='addition_seniority',
            field=models.PositiveIntegerField(default=0, verbose_name='سنواتی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='addition_system',
            field=models.PositiveIntegerField(default=0, verbose_name='سامانه'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='addition_total',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع اضافه خدمت'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='calculate_until_date',
            field=models.DateField(blank=True, null=True, verbose_name='محاسبه تا تاریخ'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='main_service_days',
            field=models.PositiveIntegerField(default=0, verbose_name='خدمت اصلی به روز'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='mandatory_service_months',
            field=models.PositiveIntegerField(default=0, verbose_name='خدمت دوره ضرورت (به ماه)'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_bsj',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری بسیج'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_children',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری فرزند'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_disability',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری جانبازی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_non_local',
            field=models.PositiveIntegerField(default=0, verbose_name='کسر غیربومی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_operational_areas',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری مناطق عملیاتی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_other',
            field=models.PositiveIntegerField(default=0, verbose_name='غیره'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_project',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری پروژه'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_seniority',
            field=models.PositiveIntegerField(default=0, verbose_name='بخشش سنواتی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_spouse',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری همسر'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_system_adjustment',
            field=models.PositiveIntegerField(default=0, verbose_name='تطبیق با سامانه'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_total',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع کسری خدمت'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='reduction_veterans',
            field=models.PositiveIntegerField(default=0, verbose_name='کسری رزمندگان'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='secondary_service_days',
            field=models.PositiveIntegerField(default=0, verbose_name='کمکی (خدمت اصلی)'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان خدمت اصلی'),
        ),
        migrations.AddField(
            model_name='soldierservice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعزام'),
        ),
    ]
