# Generated by Django 5.1.4 on 2025-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_service_apps', '0002_remove_soldierservice_khod_dore_senavati_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierservice',
            name='main_service_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='خدمت اصلی به روز'),
        ),
        migrations.AlterField(
            model_name='soldierservice',
            name='mandatory_service_months',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='خدمت دوره ضرورت (به ماه)'),
        ),
        migrations.AlterField(
            model_name='soldierservice',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='soldierservice',
            name='secondary_service_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='کمکی (خدمت اصلی)'),
        ),
    ]
