# Generated by Django 5.1.4 on 2025-05-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_service_apps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierservice',
            name='actual_service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='پایان خدمت اصلی(یاکسر و اضافه خدمت)'),
        ),
        migrations.AlterField(
            model_name='soldierservice',
            name='service_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان خدمت اصلی(بدون کسر و اضافه خدمت)'),
        ),
    ]
