# Generated by Django 5.1.4 on 2025-05-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldier_service_apps', '0003_alter_soldierservice_actual_service_end_date_and_more'),
        ('soldires_apps', '0022_soldier_eye_color_soldier_hair_color_soldier_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldierservice',
            name='soldier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='soldires_apps.soldier'),
        ),
    ]
