# Generated by Django 5.1.4 on 2025-04-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities_iran_manager_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='province',
            name='slug',
        ),
    ]
