# Generated by Django 5.1.4 on 2025-02-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_iran_manager_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='مسافت'),
        ),
        migrations.AddField(
            model_name='province',
            name='native',
            field=models.BooleanField(default=False, verbose_name='بومی'),
        ),
    ]
