# Generated by Django 5.1.4 on 2025-04-27 20:31

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_center_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.PositiveIntegerField(unique=True, verbose_name='کد سازمانی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('id_card_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پاسداری')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('birth_place', models.CharField(max_length=100, verbose_name='محل تولد')),
                ('issuance_place', models.CharField(max_length=100, verbose_name='محل صدور')),
                ('marital_status', models.CharField(choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=20, verbose_name='وضعیت تاهل')),
                ('number_of_children', models.PositiveIntegerField(default=0, verbose_name='تعداد اولاد')),
                ('health_status', models.CharField(choices=[('سالم', 'سالم'), ('معاف از رزم', 'معاف از رزم'), ('گروه ب', 'گروه ب'), ('معاف+گروه ب', 'معاف+گروه ب')], max_length=100, verbose_name='وضعیت سلامت')),
                ('health_status_description', models.TextField(blank=True, null=True, verbose_name='توضیحات وضعیت سلامت')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='گروه خون')),
                ('naserin_group_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره گروه ناصرین')),
                ('residence_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='کیلومتر')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کدپستی')),
                ('phone_home', models.CharField(blank=True, max_length=15, null=True, verbose_name='منزل')),
                ('phone_mobile', models.CharField(max_length=15, verbose_name='موبایل')),
                ('phone_virtual', models.CharField(blank=True, max_length=15, null=True, verbose_name='همراه مجازی')),
                ('phone_parents', models.CharField(blank=True, max_length=15, null=True, verbose_name='همراه پدر یا مادر')),
                ('rank', models.CharField(choices=[('سرباز(1)', 'سرباز(1)'), ('سرباز دوم(2)', 'سرباز دوم(2)'), ('سرباز یکم(3)', 'سرباز یکم(3)'), ('رزمیار(4)', 'رزمیار(4)'), ('رزم آور سوم(5)', 'رزم آور سوم(5)'), ('رزم آور دوم(6)', 'رزم آور دوم(6)'), ('رزم آور یکم(7)', 'رزم آور یکم(7)'), ('رزمدار دوم(8)', 'رزمدار دوم(8)'), ('رزمدار یکم(9)', 'رزمدار یکم(9)'), ('ستوان سوم(10)', 'ستوان سوم(10)'), ('ستوان دوم(11)', 'ستوان دوم(11)'), ('ستوان یکم(12)', 'ستوان یکم(12)')], max_length=50, verbose_name='درجه')),
                ('is_guard_duty', models.BooleanField(default=False, verbose_name='پاسدار وظیفه')),
                ('is_fugitive', models.BooleanField(default=False, verbose_name='فراری')),
                ('fugitive_record', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='سابقه فرار')),
                ('addiction_record', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='سابقه اعتیاد')),
                ('education_major', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی')),
                ('referral_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف')),
                ('dispatch_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اعزام')),
                ('training_duration', models.PositiveIntegerField(verbose_name='مدت آموزش (روز)')),
                ('service_duration_completed', models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار خدمت انجام شده')),
                ('service_entry_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ورود به یگان')),
                ('total_service_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='مجموع (کسری/اضافه خدمت)')),
                ('service_deduction_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کسری خدمت')),
                ('service_extension_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع اضافه خدمت')),
                ('service_end_date', models.DateField(blank=True, null=True, verbose_name='پایان خدمت')),
                ('traffic_status', models.CharField(blank=True, choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], max_length=50, null=True, verbose_name='تردد')),
                ('essential_service_duration', models.PositiveIntegerField(verbose_name='مدت خدمت ضرورت')),
                ('has_driving_license', models.CharField(blank=True, choices=[('پایه سوم', 'پایه سوم')], max_length=200, null=True, verbose_name='گواهینامه دارد؟')),
                ('driving_license_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع گواهینامه')),
                ('file_shortage', models.TextField(blank=True, null=True, verbose_name='کسری پرونده')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('address', models.TextField(verbose_name='آدرس منزل')),
                ('saman_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری ثامن')),
                ('card_chip', models.CharField(blank=True, max_length=50, null=True, verbose_name='تراشه/کارت')),
                ('ideological_training_period', models.CharField(blank=True, max_length=50, null=True, verbose_name='دوره عقیدتی')),
                ('independent_married', models.BooleanField(default=False, verbose_name='متاهل مستقل')),
                ('weekly_or_monthly_presence', models.CharField(blank=True, max_length=50, null=True, verbose_name='حضور هفتگی/ماهانه')),
                ('is_needy', models.BooleanField(default=False, verbose_name='معسرین')),
                ('expertise', models.CharField(blank=True, max_length=100, null=True, verbose_name='تخصص')),
                ('is_sunni', models.BooleanField(default=False, verbose_name='اهل تسنن')),
                ('is_sayyed', models.BooleanField(default=False, verbose_name='سید')),
                ('photo_scan', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='اسکن عکس')),
                ('eligible_for_card_issuance', models.BooleanField(default=True, verbose_name='واجد شرایط صدور کارت پایان خدمت')),
                ('card_issuance_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت صدور کارت پایان خدمت')),
                ('expired_file_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرونده منقضی خدمت')),
                ('skill_5', models.CharField(blank=True, max_length=100, null=True, verbose_name='مهارت 5گانه')),
                ('skill_group', models.CharField(blank=True, choices=[('گروه 1 : پزشکی و پیراپزشکی = گروه پیراپزشکی(رادیولوژی،هوش بری،علوم آزمایشگاهی،اتاق عمل،فوریت پزشکی ،کادر درمان)', 'گروه 1 : پزشکی و پیراپزشکی = گروه پیراپزشکی(رادیولوژی،هوش بری،علوم آزمایشگاهی،اتاق عمل،فوریت پزشکی ،کادر درمان)'), ('گروه 2 : تحصیلات تکمیلی و غیرپزشکی = فوق لیسانس، دکتری و فوق دکتری', 'گروه 2 : تحصیلات تکمیلی و غیرپزشکی = فوق لیسانس، دکتری و فوق دکتری'), ('گروه 3 : لیسانس = در صورت بکارگیری در پست مرتبط با تحصیلات ،عدم نیاز به آموزش', 'گروه 3 : لیسانس = در صورت بکارگیری در پست مرتبط با تحصیلات ،عدم نیاز به آموزش'), ('گروه 4 : فوق دیپلم و دیپلم فنی و حرفه ای و کاردانش', 'گروه 4 : فوق دیپلم و دیپلم فنی و حرفه ای و کاردانش'), ('گروه 5 : فوق دیپلم و دیپلم به پایین', 'گروه 5 : فوق دیپلم و دیپلم به پایین'), ('گروه 6 : دارندگان گواهینامه فنی و حرفه ای', 'گروه 6 : دارندگان گواهینامه فنی و حرفه ای'), ('گروه 7 : فوق دیپلم و دیپلم که در سالهای گذشته گواهینامه گرفته اند و همچنان سرباز می باشند', 'گروه 7 : فوق دیپلم و دیپلم که در سالهای گذشته گواهینامه گرفته اند و همچنان سرباز می باشند')], max_length=250, null=True, verbose_name='گروه مهارتی')),
                ('skill_certificate', models.CharField(blank=True, choices=[('مدرک 1', 'مدرک 1')], max_length=100, null=True, verbose_name='مدرک مهارتی')),
                ('number_of_certificates', models.PositiveIntegerField(default=0, verbose_name='تعداد مدرک')),
                ('is_certificate', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='مدرک مهارت آموزی دارد؟')),
                ('degree', models.CharField(blank=True, choices=[('زیردیپلم', 'زیردیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا'), ('دکترا پزشکی', 'دکترا پزشکی')], max_length=100, null=True, verbose_name='مدرک تحصیلی')),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی')),
                ('basic_training_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_center_apps.trainingcenter', verbose_name='نام آموزشگاه رزم مقدماتی')),
            ],
        ),
    ]
