# Generated by Django 5.1.4 on 2025-04-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_iran_manager_apps', '0001_initial'),
        ('soldires_apps', '0001_initial'),
        ('units_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='current_parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.parentunit', verbose_name='واحد اصلی فعلی'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='current_sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.subunit', verbose_name='زیرواحد فعلی'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='organizational_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soldires_apps.organizationalcode', verbose_name='کد سازمانی'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='residence_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_iran_manager_apps.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='residence_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_iran_manager_apps.province', verbose_name='استان'),
        ),
    ]
