# Generated by Django 5.1.4 on 2024-12-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0001_initial'),
        ('units_apps', '0002_alter_parentunit_options_alter_subunit_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='subunit_name',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='soldier',
            name='current_parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.parentunit', verbose_name='واحد اصلی فعلی'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='current_sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units_apps.subunit', verbose_name='زیرواحد فعلی'),
        ),
    ]
