# Generated by Django 5.1.4 on 2025-04-28 14:10

import soldires_apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='residence_distance_km',
        ),
        migrations.AlterField(
            model_name='soldier',
            name='photo_scan',
            field=models.ImageField(blank=True, null=True, upload_to=soldires_apps.models.PathAndRename('photos/'), verbose_name='اسکن عکس'),
        ),
    ]
