# Generated by Django 5.1.4 on 2024-12-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0002_remove_soldier_subunit_name_remove_soldier_unit_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='soldier',
            name='organizational_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soldires_apps.organizationalcode', verbose_name='کد سازمانی'),
        ),
    ]
