# Generated by Django 5.1.4 on 2025-01-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0003_organizationalcode_alter_soldier_organizational_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalcode',
            name='code_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='کد سازمانی'),
        ),
        migrations.AlterField(
            model_name='organizationalcode',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='health_status',
            field=models.CharField(choices=[('سالم', 'سالم'), ('معاف از رزم', 'معاف از رزم'), ('گروه ب', 'گروه ب'), ('معاف+گروه ب', 'معاف+گروه ب')], max_length=100, verbose_name='وضعیت سلامت'),
        ),
    ]
