# Generated by Django 5.1.4 on 2025-04-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0003_remove_soldier_residence_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='گروه خون'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(blank=True, choices=[('سرباز(1)', 'سرباز(1)'), ('سرباز دوم(2)', 'سرباز دوم(2)'), ('سرباز یکم(3)', 'سرباز یکم(3)'), ('رزمیار(4)', 'رزمیار(4)'), ('رزم آور سوم(5)', 'رزم آور سوم(5)'), ('رزم آور دوم(6)', 'رزم آور دوم(6)'), ('رزم آور یکم(7)', 'رزم آور یکم(7)'), ('رزمدار دوم(8)', 'رزمدار دوم(8)'), ('رزمدار یکم(9)', 'رزمدار یکم(9)'), ('ستوان سوم(10)', 'ستوان سوم(10)'), ('ستوان دوم(11)', 'ستوان دوم(11)'), ('ستوان یکم(12)', 'ستوان یکم(12)')], max_length=50, null=True, verbose_name='درجه'),
        ),
    ]
