# Generated by Django 5.1.4 on 2025-01-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0004_alter_organizationalcode_code_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='introduction_letter_scan',
        ),
    ]
