# Generated by Django 5.1.4 on 2025-05-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0004_alter_soldier_blood_group_alter_soldier_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='independent_married',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='متاهل مستقل'),
        ),
    ]
