# Generated by Django 5.1.4 on 2025-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0005_remove_soldier_introduction_letter_scan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='residence',
        ),
        migrations.AddField(
            model_name='soldier',
            name='residence_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شهر محل سکونت'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='residence_province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='استان محل سکونت'),
        ),
    ]
