# Generated by Django 5.1.4 on 2025-05-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0005_alter_soldier_independent_married'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='is_certificate',
            field=models.BooleanField(blank=True, choices=[(True, 'بله'), (False, 'خیر')], default=False, null=True, verbose_name='مدرک مهارت آموزی دارد؟'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='number_of_certificates',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد مدرک'),
        ),
    ]
