# Generated by Django 5.1.4 on 2025-02-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0006_remove_soldier_residence_soldier_residence_city_and_more'),
        ('training_center_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='basic_training_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_center_apps.trainingcenter', verbose_name='نام آموزشگاه رزم مقدماتی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(choices=[('سرباز', 'سرباز')], max_length=50, verbose_name='درجه'),
        ),
    ]
