# Generated by Django 5.1.4 on 2025-05-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0006_alter_soldier_is_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعزام'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='service_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود به یگان'),
        ),
    ]
