# Generated by Django 5.1.4 on 2025-02-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0007_alter_soldier_basic_training_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی'),
        ),
    ]
