# Generated by Django 5.1.4 on 2025-05-11 04:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0007_alter_soldier_birth_date_alter_soldier_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='driving_license_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('پایه سوم', 'پایه سوم'), ('پایه دوم', 'پایه دوم'), ('پایه اول', 'پایه اول'), ('موتورسیکلت', 'موتورسیکلت'), ('ویژه', 'ویژه'), ('ندارد', 'ندارد')], max_length=200, null=True, verbose_name='نوع گواهینامه'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='has_driving_license',
            field=models.CharField(blank=True, choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], max_length=200, null=True, verbose_name='گواهینامه دارد؟'),
        ),
    ]
