# Generated by Django 5.1.4 on 2025-05-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0008_alter_soldier_driving_license_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='education_major',
        ),
        migrations.AddField(
            model_name='soldier',
            name='absorption',
            field=models.BooleanField(default=False, verbose_name='جذبی؟'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='referral_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معرف'),
        ),
    ]
