# Generated by Django 5.1.4 on 2025-02-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0008_soldier_degree_soldier_field_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldier',
            name='need_certificate',
        ),
        migrations.AddField(
            model_name='soldier',
            name='is_certificate',
            field=models.BooleanField(choices=[('بله', 'بله'), ('خیر', 'خیر')], default=False, verbose_name='مدرک مهارت آموزی دارد؟'),
        ),
    ]
