# Generated by Django 5.1.4 on 2025-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0009_remove_soldier_education_major_soldier_absorption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='marital_status',
            field=models.CharField(choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='traffic_status',
            field=models.CharField(blank=True, choices=[('روزانه', 'روزانه'), ('هفتگی', 'هفتگی'), ('ماهانه', 'ماهانه')], max_length=50, null=True, verbose_name='تردد'),
        ),
    ]
