# Generated by Django 5.1.4 on 2025-02-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0010_alter_soldier_skill_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='service_entry_date',
            field=models.DateField(verbose_name='تاریخ ورود به یگان'),
        ),
    ]
