# Generated by Django 5.1.4 on 2025-05-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_naserin_apps', '0002_alter_naseringroup_description_and_more'),
        ('soldires_apps', '0010_alter_soldier_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='naserin_group_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soldire_naserin_apps.naseringroup', verbose_name='شماره گروه ناصرین'),
        ),
    ]
