# Generated by Django 5.1.4 on 2025-02-16 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_iran_manager_apps', '0002_city_distance_province_native'),
        ('soldires_apps', '0011_alter_soldier_service_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='residence_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_iran_manager_apps.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='residence_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_iran_manager_apps.province', verbose_name='استان'),
        ),
    ]
