# Generated by Django 5.1.4 on 2025-02-16 20:05

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0012_alter_soldier_residence_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='dispatch_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ اعزام'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='has_driving_license',
            field=models.CharField(blank=True, choices=[('پایه سوم', 'پایه سوم')], max_length=200, null=True, verbose_name='گواهینامه دارد؟'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='service_entry_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ورود به یگان'),
        ),
    ]
