# Generated by Django 5.1.4 on 2025-05-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0012_remove_soldier_naserin_group_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=20, null=True, verbose_name='وضعیت تاهل'),
        ),
    ]
