# Generated by Django 5.1.4 on 2025-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0013_alter_soldier_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='Is_the_Basij_sufficient',
            field=models.BooleanField(default=False, verbose_name='کفایتدار بسیج'),
        ),
    ]
