# Generated by Django 5.1.4 on 2025-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0013_alter_soldier_birth_date_alter_soldier_dispatch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='addiction_record',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='سابقه اعتیاد'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='education_major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='fugitive_record',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='سابقه فرار'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='is_certificate',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='مدرک مهارت آموزی دارد؟'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='residence_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='کیلومتر'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='service_duration_completed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مقدار خدمت انجام شده'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='total_service_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='مجموع (کسری/اضافه خدمت)'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='traffic_status',
            field=models.CharField(blank=True, choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], max_length=50, null=True, verbose_name='تردد'),
        ),
    ]
