# Generated by Django 5.1.4 on 2025-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0014_alter_soldier_addiction_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='degree',
            field=models.CharField(blank=True, choices=[('زیردیپلم', 'زیردیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا'), ('دکترا پزشکی', 'دکترا پزشکی')], max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='rank',
            field=models.CharField(choices=[('سرباز(1)', 'سرباز(1)'), ('سرباز دوم(2)', 'سرباز دوم(2)'), ('سرباز یکم(3)', 'سرباز یکم(3)'), ('رزمیار(4)', 'رزمیار(4)'), ('رزم آور سوم(5)', 'رزم آور سوم(5)'), ('رزم آور دوم(6)', 'رزم آور دوم(6)'), ('رزم آور یکم(7)', 'رزم آور یکم(7)'), ('رزمدار دوم(8)', 'رزمدار دوم(8)'), ('رزمدار یکم(9)', 'رزمدار یکم(9)'), ('ستوان سوم(10)', 'ستوان سوم(10)'), ('ستوان دوم(11)', 'ستوان دوم(11)'), ('ستوان یکم(12)', 'ستوان یکم(12)')], max_length=50, verbose_name='درجه'),
        ),
    ]
