# Generated by Django 5.1.4 on 2025-05-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0014_soldier_is_the_basij_sufficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='total_service_adjustment',
            field=models.IntegerField(blank=True, null=True, verbose_name='مجموع (کسری/اضافه خدمت)'),
        ),
    ]
