# Generated by Django 5.1.4 on 2025-05-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0015_alter_soldier_total_service_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='service_deduction_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نوع کسری خدمت'),
        ),
    ]
