# Generated by Django 5.1.4 on 2025-05-12 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldire_religious_period_apps', '0001_initial'),
        ('soldires_apps', '0016_alter_soldier_service_deduction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='ideological_training_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soldire_religious_period_apps.religiousperiod', verbose_name='دوره عقیدتی'),
        ),
    ]
