# Generated by Django 5.1.4 on 2025-05-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0018_alter_soldier_ideological_training_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_non_issuance', models.TextField(blank=True, null=True, verbose_name='علت عدم صدور')),
                ('total_debt_rial', models.BigIntegerField(default=0, verbose_name='میزان بدهی (ریال)')),
                ('current_debt_rial', models.BigIntegerField(default=0, verbose_name='بدهی باقی\u200cمانده (ریال)')),
                ('last_rights_check_date', models.DateField(blank=True, null=True, verbose_name='اخرین تاریخ بررسی حقوق')),
                ('need_rights_recheck', models.BooleanField(default=True, verbose_name='نیاز به بررسی مجدد حقوق')),
                ('final_settlement_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت تسویه در سامانه')),
                ('card_issued', models.BooleanField(default=False, verbose_name='کارت صادر شده؟')),
                ('card_issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ثبت صدور کارت در سامانه')),
                ('card_series', models.CharField(blank=True, max_length=50, null=True, verbose_name='سری کارت')),
                ('card_issue_count', models.PositiveIntegerField(default=1, verbose_name='دفعات تکرار در لیست')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تسویه'), ('partial', 'تسویه ناقص'), ('cleared', 'تسویه کامل')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soldier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='soldires_apps.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rial', models.BigIntegerField(verbose_name='مبلغ واریزی (ریال)')),
                ('receipt_number', models.CharField(max_length=100, verbose_name='شماره فیش واریزی')),
                ('deposit_date', models.DateField(verbose_name='تاریخ فیش واریزی')),
                ('bank_operator_code', models.CharField(max_length=50, verbose_name='کد متصدی بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='soldires_apps.settlement')),
            ],
        ),
    ]
