# Generated by Django 5.1.4 on 2025-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0019_settlement_paymentreceipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='card_issue_count',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='card_issue_date',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='card_issued',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='card_series',
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='فایل فیش'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تسویه'), ('partial', 'تسویه ناقص'), ('cleared', 'تسویه کامل'), ('transitional', 'انتقالی'), ('review', 'بررسی')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
