# Generated by Django 5.1.4 on 2025-05-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0020_remove_settlement_card_issue_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='health_status',
            field=models.CharField(blank=True, choices=[('سالم', 'سالم'), ('معاف از رزم', 'معاف از رزم'), ('گروه ب', 'گروه ب'), ('معاف+گروه ب', 'معاف+گروه ب')], max_length=100, null=True, verbose_name='وضعیت سلامت'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='issuance_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='محل صدور'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
