# Generated by Django 5.1.4 on 2025-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0021_alter_soldier_birth_place_alter_soldier_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='eye_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رنگ چشم'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='hair_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رنگ مو'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='height',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='قد'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وزن'),
        ),
    ]
