# Generated by Django 5.1.4 on 2025-05-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0022_soldier_eye_color_soldier_hair_color_soldier_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_checked_out',
            field=models.BooleanField(default=False, verbose_name='تسویه حساب'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='status',
            field=models.CharField(blank=True, choices=[('توجیحی', 'توجیحی'), ('حین خدمت', 'حین خدمت'), ('پایان خدمت', 'پایان خدمت'), ('انتقالی', 'انتقالی'), ('قبولی در دانشگاه', 'قبولی در دانشگاه'), ('استخدام در نیروهای مسلح', 'استخدام در نیروهای مسلح')], max_length=200, null=True, verbose_name='وضعیت فرد'),
        ),
    ]
