# Generated by Django 5.1.4 on 2025-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0023_soldier_is_checked_out_soldier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='deposit_date',
            field=models.CharField(max_length=120, verbose_name='تاریخ فیش واریزی'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('review', 'بررسی حقوق'), ('pending', 'در انتظار تسویه'), ('partial', 'تسویه ناقص'), ('cleared', 'تسویه کامل'), ('transferred', 'انتقالی')], default='review', max_length=20, verbose_name='وضعیت'),
        ),
    ]
