# Generated by Django 5.2.7 on 2025-11-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0024_alter_paymentreceipt_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='organizational_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_soldier', to='soldires_apps.organizationalcode', verbose_name='کد سازمانی'),
        ),
    ]
