# Generated by Django 5.2.7 on 2025-11-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0025_alter_soldier_organizational_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalcode',
            name='current_soldier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_code', to='soldires_apps.soldier', verbose_name='سرباز فعلی'),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='organizational_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldiers', to='soldires_apps.organizationalcode', verbose_name='کد سازمانی'),
        ),
    ]
