# Generated by Django 5.2.7 on 2025-11-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational_position', '0001_initial'),
        ('soldires_apps', '0026_organizationalcode_current_soldier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soldiers', to='organizational_position.organizationalposition', verbose_name='جایگاه سازمانی'),
        ),
        migrations.AddField(
            model_name='soldier',
            name='position_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انتصاب به جایگاه'),
        ),
    ]
