# Generated by Django 5.2.7 on 2025-11-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0027_soldier_position_soldier_position_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='system_presence',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='اعلام حضور سامانه'),
        ),
    ]
