# Generated by Django 5.1.1 on 2025-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0028_soldier_system_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='degree',
            field=models.CharField(blank=True, choices=[('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا'), ('دکترا پزشکی', 'دکترا پزشکی')], max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
    ]
