# Generated by Django 5.1.1 on 2025-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldires_apps', '0029_alter_soldier_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='is_top5',
            field=models.BooleanField(blank=True, choices=[(True, 'بله'), (False, 'خیر')], default=False, null=True, verbose_name='برتر'),
        ),
    ]
