# Generated by Django 5.1.1 on 2025-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasdar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد پاسداری')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='شماره ملی')),
                ('birth_certificate_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه')),
                ('section', models.CharField(blank=True, max_length=50, null=True, verbose_name='قسمت حاضر')),
                ('role_in_section', models.CharField(blank=True, max_length=50, null=True, verbose_name='نقش در قسمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
